---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

title: Homepage - /forge
color: slate
headerStyle: boxed
target: _blank
hideVersion: true
theme: dark
showState: true
favicon: https://github.com/Xavier2p/assets/blob/main/forge-logos/colors.png?raw=true
iconStyle: theme

layout:
  stats/:
    style: row
    columns: 3
    icon: mdi-network-pos
  network/:
    style: row
    icon: mdi-lan
    columns: 4
  cloud/:
    icon: mdi-wan
    style: row
    columns: 4
  admin/:
    icon: mdi-security-network
    columns: 2
  media/:
    icon: mdi-play-network
  downloads/:
    icon: mdi-download-network
